import { Geist, Geist_Mono, Antonio } from "next/font/google";
import "./globals.css";
import GsapPlugins from "@/utils/GsapPlugins";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const antonio = Antonio({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${antonio.variable}  antialiased`}
      >
        <GsapPlugins />
        {children}
      </body>
    </html>
  );
}
